import { FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { apiFetch, clearToken, setToken } from "./lib/apiClient";

type Locale = "zh-CN" | "en" | "ja" | "zh-Hant";
type Brand = "JINÉ" | "NÉSHA";

const labels: Record<Locale, string> = { en: "EN", "zh-CN": "简", "zh-Hant": "繁", ja: "日" };
const copy = {
  "zh-CN": { works: "作品", silhouette: "廓形", materials: "材质", atelier: "工坊", appointment: "预约", account: "账户", explore: "探索", begin: "开始订购", save: "保存暂存", next: "下一步", back: "上一步", heroA: "同一廓形。", heroB: "无尽表达。", heroBody: "以材料、步态与手工艺重新理解一件礼服。", collection: "作品系列", all: "全部", configure: "配置您的作品", orders: "我的订单", draft: "暂存中的订购" },
  en: { works: "Works", silhouette: "Silhouette", materials: "Materials", atelier: "Atelier", appointment: "Appointment", account: "Account", explore: "Explore", begin: "Begin order", save: "Save draft", next: "Next", back: "Back", heroA: "One Silhouette.", heroB: "Endless Expressions.", heroBody: "A dress reconsidered through material, movement and craft.", collection: "The Works", all: "All", configure: "Configure your work", orders: "My orders", draft: "Draft order" },
  ja: { works: "作品", silhouette: "シルエット", materials: "素材", atelier: "工房", appointment: "予約", account: "アカウント", explore: "作品を見る", begin: "注文を開始", save: "下書きを保存", next: "次へ", back: "戻る", heroA: "ひとつのシルエット、", heroB: "無限の表現。", heroBody: "素材、動き、手仕事から一着のドレスを見つめ直す。", collection: "コレクション", all: "すべて", configure: "作品を構成する", orders: "注文", draft: "保存中の注文" },
  "zh-Hant": { works: "作品", silhouette: "廓形", materials: "材質", atelier: "工坊", appointment: "預約", account: "帳戶", explore: "探索", begin: "開始訂購", save: "儲存暫存", next: "下一步", back: "上一步", heroA: "同一廓形。", heroB: "無盡表達。", heroBody: "以材質、步態與手工藝重新理解一件禮服。", collection: "作品系列", all: "全部", configure: "配置您的作品", orders: "我的訂單", draft: "暫存中的訂購" },
} as const;

const works = Array.from({ length: 24 }, (_, index) => {
  const brand: Brand = index < 12 ? "JINÉ" : "NÉSHA";
  const number = (index % 12) + 1;
  const suffixes = ["pale_celadon_silk_jacquard", "oat_white_raw_silk", "smoke_blue_grey_silk_crepe", "soft_taupe_silk_faille", "bone_white_matte_silk", "platinum_grey_double_crepe"];
  const file = brand === "NÉSHA" || number <= 6 ? `${brand === "JINÉ" ? "JINE" : "NESHA"}_${String(number).padStart(2, "0")}.png` : `JINE_${String(number).padStart(2, "0")}_${suffixes[number - 7]}.png`;
  return { id: `${brand === "JINÉ" ? "jine" : "nesha"}-${String(number).padStart(2, "0")}`, brand, number, title: brand === "JINÉ" ? `Moon White ${String(number).padStart(2, "0")}` : `Living Art ${String(number).padStart(2, "0")}`, subtitle: brand === "JINÉ" ? "Quiet line · Silk structure" : "Collectible line · Hand-finished surface", price: brand === "JINÉ" ? 999 : 2999, image: `/assets/works/${file}` };
});

const materialCards = [
  { title: "Suzhou Embroidery", cn: "苏绣", body: "Silk thread drawn through translucent ground, mapped to the garment rather than applied as ornament.", image: "/assets/materials/su-embroidery.jpg" },
  { title: "Xiangyunsha", cn: "香云纱", body: "A patient sequence of dye, sun and river mud gives silk its quiet, living depth.", image: "/assets/materials/xiangyunsha-process.jpg" },
  { title: "Silk Weaving", cn: "丝织", body: "Density, lustre and hand are selected together so the cloth supports the intended movement.", image: "/assets/materials/silk-weaving.jpg" },
];

function usePath() {
  const [path, setPath] = useState(location.pathname || "/");
  useEffect(() => { const onPop = () => setPath(location.pathname || "/"); addEventListener("popstate", onPop); return () => removeEventListener("popstate", onPop); }, []);
  const navigate = (to: string) => { history.pushState({}, "", to); setPath(to.split("?")[0]); scrollTo({ top: 0, behavior: "smooth" }); };
  return { path, navigate };
}

function Anchor({ to, navigate, className, children }: { to: string; navigate: (to: string) => void; className?: string; children: ReactNode }) {
  return <a className={className} href={to} onClick={(event) => { event.preventDefault(); navigate(to); }}>{children}</a>;
}

function LanguageSwitch({ locale, onChange }: { locale: Locale; onChange: (locale: Locale) => void }) {
  return <div className="language-switch" aria-label="Language">{(Object.keys(labels) as Locale[]).map((key) => <button className={locale === key ? "active" : ""} key={key} onClick={() => onChange(key)} aria-pressed={locale === key}>{labels[key]}</button>)}</div>;
}

function Header({ locale, onLocale, navigate }: { locale: Locale; onLocale: (locale: Locale) => void; navigate: (to: string) => void }) {
  const [open, setOpen] = useState(false); const t = copy[locale];
  return <header className="site-header"><Anchor to="/" navigate={navigate} className="wordmark">JINÉ / NÉSHA</Anchor><button className="menu-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Menu"><span /><span /></button><nav className={open ? "site-nav open" : "site-nav"} onClick={() => setOpen(false)}><Anchor to="/works" navigate={navigate}>{t.works}</Anchor><Anchor to="/works?brand=jine" navigate={navigate}>JINÉ</Anchor><Anchor to="/works?brand=nesha" navigate={navigate}>NÉSHA</Anchor><Anchor to="/silhouette" navigate={navigate}>{t.silhouette}</Anchor><Anchor to="/materials" navigate={navigate}>{t.materials}</Anchor><Anchor to="/atelier" navigate={navigate}>{t.atelier}</Anchor><Anchor to="/appointment" navigate={navigate}>{t.appointment}</Anchor></nav><div className="header-tools"><LanguageSwitch locale={locale} onChange={onLocale} /><Anchor to="/account" navigate={navigate}>{t.account}</Anchor></div></header>;
}

function Footer({ locale, navigate }: { locale: Locale; navigate: (to: string) => void }) {
  const t = copy[locale]; return <footer className="footer"><div><div className="footer-mark">JINÉ / NÉSHA</div><p>{t.works}　{t.silhouette}　{t.materials}　{t.atelier}　{t.appointment}</p></div><p className="footer-manifesto">A living design system for<br />quiet luxury and collectible craft.</p><div className="footer-account"><Anchor to="/account" navigate={navigate}>{t.account} →</Anchor><small>© 2026 JINÉ / NÉSHA</small></div></footer>;
}

function SiteShell({ locale, onLocale, navigate, children }: { locale: Locale; onLocale: (locale: Locale) => void; navigate: (to: string) => void; children: ReactNode }) { return <><Header locale={locale} onLocale={onLocale} navigate={navigate} /><main>{children}</main><Footer locale={locale} navigate={navigate} /></>; }

function Home({ locale, navigate }: { locale: Locale; navigate: (to: string) => void }) {
  const t = copy[locale]; const videoRef = useRef<HTMLVideoElement>(null); const [paused, setPaused] = useState(false); const mediaBase = (import.meta.env.VITE_MEDIA_BASE_URL ?? "/media").replace(/\/$/, "");
  const toggle = () => { const video = videoRef.current; if (!video) return; if (video.paused) video.play().catch(() => undefined); else video.pause(); setPaused(!video.paused); };
  return <><section className="runway-hero"><video ref={videoRef} autoPlay muted loop playsInline poster="/assets/editorial/jine-hero.png"><source src={`${mediaBase}/JINE_NESHA_HOMEPAGE_LOOP_52S_NO_TITLE_720P.mp4`} type="video/mp4" /></video><div className="hero-shade" /><p className="eyebrow hero-eyebrow">RUNWAY FILM　01</p><h1><span>{t.heroA}</span><span>{t.heroB}</span></h1><p className="hero-caption">JINÉ | NÉSHA · COLLECTION FILM 2026</p><button className="film-control" onClick={toggle} aria-label={paused ? "Play film" : "Pause film"}>{paused ? "▶" : "Ⅱ"}</button><div className="film-line"><i /></div><span className="film-mode">AUTOPLAY · MUTED · LOOP</span></section><section className="brand-entrances"><Anchor to="/works/jine-01" navigate={navigate} className="brand-entrance"><img src="/assets/editorial/jine-hero.png" alt="JINÉ Moon White formalwear" /><span>THE QUIET LINE</span><strong>JINÉ</strong><em>{t.explore} →</em></Anchor><Anchor to="/works/nesha-01" navigate={navigate} className="brand-entrance"><img src="/assets/editorial/nesha-hero.png" alt="NÉSHA embroidered formalwear" /><span>THE COLLECTIBLE LINE</span><strong>NÉSHA</strong><em>{t.explore} →</em></Anchor></section><section className="manifesto"><p className="eyebrow">SHOW NOTES · 2026</p><h2>{t.heroA}<br />{t.heroB}</h2><div><p>{t.heroBody}</p><strong>One Silhouette. Endless Expressions.</strong></div></section></>;
}

function PageIntro({ kicker, title, body }: { kicker: string; title: string; body: string }) { return <section className="page-intro"><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{body}</p></section>; }

function WorksPage({ locale, navigate }: { locale: Locale; navigate: (to: string) => void }) {
  const requested = new URLSearchParams(location.search).get("brand"); const [filter, setFilter] = useState<"all" | "jine" | "nesha">(requested === "jine" || requested === "nesha" ? requested : "all"); const t = copy[locale];
  const shown = works.filter((work) => filter === "all" || work.id.startsWith(filter));
  return <><PageIntro kicker="JINÉ / NÉSHA · 01—24" title={t.collection} body={locale === "en" ? "Two lines share one disciplined silhouette. Material and handwork decide the expression." : "两个系列共享同一克制廓形，由材料与手工艺决定不同表达。"} /><div className="filter-bar"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>{t.all}</button><button className={filter === "jine" ? "active" : ""} onClick={() => setFilter("jine")}>JINÉ</button><button className={filter === "nesha" ? "active" : ""} onClick={() => setFilter("nesha")}>NÉSHA</button></div><section className="works-grid">{shown.map((work) => <Anchor key={work.id} to={`/works/${work.id}`} navigate={navigate} className="work-card"><div className="work-image"><img src={work.image} alt={`${work.brand} ${work.title}`} loading="lazy" /></div><div><p>{work.brand} · {String(work.number).padStart(2, "0")}</p><h2>{work.title}</h2><span>{work.subtitle}</span><b>USD {work.price.toLocaleString()}</b></div></Anchor>)}</section></>;
}

function WorkDetail({ id, locale, navigate }: { id: string; locale: Locale; navigate: (to: string) => void }) {
  const work = works.find((item) => item.id === id) ?? works[0]; const family = works.filter((item) => item.brand === work.brand).slice(0, 6); const t = copy[locale];
  return <><section className="product-hero"><div className="product-copy"><p className="eyebrow">{work.brand} · WORK {String(work.number).padStart(2, "0")}</p><h1>{work.title}</h1><p>{work.brand === "JINÉ" ? "A quiet architecture in silk. Clean from a distance, exact in every seam." : "A composed field for woven surface and hand embroidery, balanced by a lucid line."}</p><b>USD {work.price.toLocaleString()}</b><button className="primary" onClick={() => navigate(`/configure/${work.id}`)}>{t.begin}</button></div><img src={work.image} alt={`${work.brand} ${work.title}`} /></section><section className="detail-note"><p className="eyebrow">FORM / MATERIAL / MOVEMENT</p><h2>Designed to be read in motion.</h2><p>The silhouette is constant enough to become recognisable, and open enough for material, finish and craft to change its character.</p></section><section className="detail-gallery">{family.map((item, index) => <img key={item.id} className={index % 3 === 0 ? "wide" : ""} src={item.image} alt={`${item.brand} view ${index + 1}`} loading="lazy" />)}</section><section className="detail-cta"><h2>{t.configure}</h2><p>Five deliberate decisions, saved as you move.</p><button className="primary inverse" onClick={() => navigate(`/configure/${work.id}`)}>{t.begin}</button></section></>;
}

function SilhouettePage() { return <><PageIntro kicker="FORM · 01" title="One silhouette, held with precision." body="A vertical line, a controlled waist and an ease designed for movement—not a seasonal shape, but a lasting foundation." /><section className="split-editorial"><img src="/assets/editorial/jine-hero.png" alt="JINÉ structural ivory silhouette" /><div><p className="eyebrow">THE MASTER SILHOUETTE</p><h2>Quiet from afar.<br />Exact up close.</h2><ul><li>Balanced shoulder and standing collar</li><li>Curved seam architecture</li><li>Measured waist with walking ease</li><li>Midi and full-length expressions</li></ul></div></section></>; }
function MaterialsPage() { return <><PageIntro kicker="MATERIAL · CRAFT" title="The surface carries the story." body="Silk is selected as structure, light and movement. Craft is planned with the garment—not added after it." /><section className="material-list">{materialCards.map((item, index) => <article key={item.title} className={index % 2 ? "reverse" : ""}><img src={item.image} alt={item.title} loading="lazy" /><div><span>{item.cn} · {String(index + 1).padStart(2, "0")}</span><h2>{item.title}</h2><p>{item.body}</p></div></article>)}</section></>; }
function AtelierPage() { return <><section className="atelier-hero"><img src="/assets/materials/silk-weaving.jpg" alt="Silk being woven" /><div><p className="eyebrow">THE ATELIER</p><h1>Made through a chain of visible decisions.</h1></div></section><section className="process-grid">{["Pattern", "Material", "Cutting", "Structure", "Craft", "Finishing"].map((step, index) => <article key={step}><span>{String(index + 1).padStart(2, "0")}</span><h2>{step}</h2><p>Each stage is recorded, confirmed and carried forward before the next begins.</p></article>)}</section></>; }

function AppointmentPage() {
  const [sent, setSent] = useState(false); const submit = (event: FormEvent) => { event.preventDefault(); setSent(true); };
  return <section className="appointment-page"><div><p className="eyebrow">PRIVATE APPOINTMENT</p><h1>A considered beginning.</h1><p>Meet with an advisor online or in the atelier to discuss silhouette, material, occasion and timeline.</p><p className="contact-note">Appointments are confirmed by a human advisor. No commitment is made until your requirements and timing are reviewed.</p></div>{sent ? <div className="success-panel"><span>✓</span><h2>Request received.</h2><p>An advisor will reply with available times.</p></div> : <form onSubmit={submit} className="appointment-form"><label>Name<input required name="name" /></label><label>Email<input required name="email" type="email" /></label><label>Preferred format<select name="format"><option>Online consultation</option><option>Atelier visit</option></select></label><label>Preferred date<input required name="date" type="date" /></label><label>What would you like to discuss?<textarea name="notes" rows={5} /></label><button className="primary">Request appointment</button></form>}</section>;
}

const configSteps = [
  { key: "fabric", title: "选择面料", en: "Select fabric", options: ["Moon White Silk", "Oat White Raw Silk", "Mist Grey Twill"] },
  { key: "lining", title: "选择里料", en: "Select lining", options: ["Tea White Habotai", "Ivory Crepe", "Mist Grey Twill"] },
  { key: "trim", title: "选择细节", en: "Select detail", options: ["Clean finish", "Hand piping", "Jade clasp"] },
  { key: "craft", title: "选择工艺", en: "Select craft", options: ["Pure line", "Silk couching", "Suzhou embroidery"] },
  { key: "review", title: "确认配置", en: "Review", options: [] },
];

function Configurator({ workId, locale, navigate }: { workId: string; locale: Locale; navigate: (to: string) => void }) {
  const work = works.find((item) => item.id === workId) ?? works[0]; const key = `jn-draft-${work.id}`; const [step, setStep] = useState(0); const [choices, setChoices] = useState<Record<string, string>>(() => { try { return JSON.parse(localStorage.getItem(key) || "{}"); } catch { return {}; } }); const [saved, setSaved] = useState(false); const t = copy[locale]; const current = configSteps[step];
  useEffect(() => { localStorage.setItem(key, JSON.stringify(choices)); setSaved(true); const timer = setTimeout(() => setSaved(false), 1400); return () => clearTimeout(timer); }, [choices, key]);
  return <section className="configurator"><div className="config-progress"><div style={{ width: `${((step + 1) / 5) * 100}%` }} /><ol>{configSteps.map((item, index) => <li key={item.key} className={index <= step ? "active" : ""}><span>{index < step ? "✓" : index + 1}</span>{item.en}</li>)}</ol></div><div className="config-main"><div className="config-heading"><p>{work.brand} · SKU {work.id.toUpperCase()}</p><span>{saved ? "● 已自动暂存" : "○ Draft saved"}</span><h1>{locale === "en" ? current.en : current.title}</h1><small>{locale === "en" ? `Step ${step + 1} / 5` : `步骤 ${step + 1} / 5`}</small></div>{step < 4 ? <div className="option-grid">{current.options.map((option, index) => <button key={option} className={choices[current.key] === option ? "option selected" : "option"} onClick={() => setChoices((value) => ({ ...value, [current.key]: option }))}><i className={`swatch swatch-${step}-${index}`} /><strong>{option}</strong><span>{index === 0 ? "Light · Breathable" : index === 1 ? "Stable · Soft drape" : "Fine · Low lustre"}</span></button>)}</div> : <div className="review-card"><img src={work.image} alt={work.title} /><div><p className="eyebrow">YOUR CONFIGURATION</p><h2>{work.brand} · {work.title}</h2>{Object.entries(choices).map(([field, value]) => <p key={field}><span>{field}</span><b>{value}</b></p>)}<p><span>Estimate</span><b>USD {work.price.toLocaleString()}</b></p></div></div>}<aside className="current-config"><span>当前配置</span><p>{Object.values(choices).join(" / ") || "尚未选择"}</p></aside><div className="config-actions"><button className="secondary" disabled={step === 0} onClick={() => setStep(Math.max(0, step - 1))}>{t.back}</button><button className="secondary" onClick={() => { localStorage.setItem(key, JSON.stringify(choices)); setSaved(true); }}>{t.save}</button>{step < 4 ? <button className="primary" disabled={!choices[current.key]} onClick={() => setStep(step + 1)}>{t.next}</button> : <button className="primary" onClick={() => navigate("/account")}>{t.begin}</button>}</div></div></section>;
}

function CustomerCentre({ locale, navigate }: { locale: Locale; navigate: (to: string) => void }) { const t = copy[locale]; return <section className="customer-page"><p className="eyebrow">CUSTOMER CENTRE</p><h1>您好，<span>Michael</span></h1><p>暂存与订单</p><h2>{t.draft}</h2><article className="draft-card"><div><h3>JINÉ · Moon White</h3><p>已完成 2 / 5 步</p><small>10 分钟前自动保存 · zh-CN</small></div><button onClick={() => navigate("/configure/jine-01")}>继续配置 →</button></article><h2>{t.orders}</h2><article className="order-card"><span>JN-260726-018</span><b>已确认</b><h3>JINÉ · Master Silhouette 01</h3><p>Moon White Silk · Clean finish</p><p>下一步：预约量体</p><button className="primary" onClick={() => navigate("/orders/JN-260726-018")}>管理订单</button></article></section>; }
function OrderDetail() { const stages = ["订单确认", "材料预留", "量体确认", "制作", "质量检查", "交付"]; return <section className="order-detail"><p className="eyebrow">ORDER · JN-260726-018</p><h1>JINÉ · Moon White</h1><div className="status-banner"><strong>已确认</strong><span>下一步：预约量体</span></div><ol className="order-timeline">{stages.map((stage, index) => <li className={index < 2 ? "done" : index === 2 ? "current" : ""} key={stage}><i>{index < 2 ? "✓" : index + 1}</i><div><h3>{stage}</h3><p>{index < 2 ? "已完成并记录" : index === 2 ? "等待客户选择预约时间" : "将在前一步完成后开始"}</p></div></li>)}</ol><div className="order-summary"><h2>Configuration</h2><p><span>Fabric</span><b>Moon White Silk</b></p><p><span>Lining</span><b>Tea White Habotai</b></p><p><span>Finish</span><b>Clean finish</b></p><p><span>Price</span><b>USD 999</b></p></div></section>; }

const adminNav = [["/admin", "Dashboard"], ["/admin/content", "Homepage"], ["/admin/content?view=products", "Product Display"], ["/admin/content?view=works", "Works"], ["/admin/sku", "SKU Step Builder"], ["/admin/translations", "Translations"], ["/admin/translations?view=publishing", "Publishing"], ["/admin/orders", "Orders"]];
function AdminShell({ navigate, children }: { navigate: (to: string) => void; children: ReactNode }) { return <div className="admin-shell"><aside className="admin-sidebar"><Anchor to="/admin" navigate={navigate} className="admin-brand">JINÉ / NÉSHA<small>ADMINISTRATION</small></Anchor><nav>{adminNav.map(([to, label]) => <Anchor key={`${to}-${label}`} to={to} navigate={navigate}>{label}</Anchor>)}</nav><footer>Prototype v1.0<br />EN / 简 / 繁 / 日</footer></aside><main className="admin-main">{children}</main></div>; }
function AdminLogin({ navigate }: { navigate: (to: string) => void }) {
  const [error, setError] = useState(""); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); try { const body = new URLSearchParams({ username: String(data.get("email")), password: String(data.get("password")) }); const base = import.meta.env.VITE_API_URL ?? "http://localhost:8000"; const response = await fetch(`${base}/api/auth/login`, { method: "POST", body, headers: { "Content-Type": "application/x-www-form-urlencoded" } }); if (!response.ok) throw new Error("Unable to sign in"); const result = await response.json(); setToken(result.access_token); navigate("/admin"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to sign in"); } };
  return <div className="admin-login"><div className="login-mark">JINÉ / NÉSHA<small>ADMINISTRATION</small></div><form onSubmit={submit}><p className="eyebrow">SECURE ACCESS</p><h1>Sign in</h1><label>Email<input type="email" name="email" required /></label><label>Password<input type="password" name="password" required /></label>{error && <p className="form-error">{error}. Check the API connection and credentials.</p>}<button className="primary">Sign in</button><button type="button" className="text-button" onClick={() => navigate("/admin")}>Preview interface →</button></form></div>;
}
function AdminDashboard({ navigate }: { navigate: (to: string) => void }) {
  const metrics = [["Published works", "12", "2 awaiting review"], ["SKU configurations", "8", "1 missing option"], ["Translation coverage", "92%", "ja: 6 fields pending"], ["Active orders", "24", "4 need attention"]]; const areas = [["Homepage Editor", "Hero, runway video, entrances", "/admin/content"], ["Product Display", "Collections and work ordering", "/admin/content?view=products"], ["Work Editor", "Content, assets, availability", "/admin/content?view=works"], ["SKU Step Builder", "Add, reorder and validate steps", "/admin/sku"], ["Translations", "zh-CN / en / ja coverage", "/admin/translations"], ["Publishing", "Review, schedule, rollback", "/admin/translations?view=publishing"], ["Orders", "Status, appointments, payments", "/admin/orders"], ["Audit Log", "Who changed what and when", "/admin/orders?view=audit"]];
  return <><div className="admin-heading"><h1>Dashboard</h1><p>内容状态、SKU 配置、翻译完整度、发布与订单一览</p></div><section className="metric-grid">{metrics.map(([label, value, note]) => <article key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section><h2 className="admin-section-title">工作区</h2><section className="workspace-grid">{areas.map(([title, note, to]) => <button key={title} onClick={() => navigate(to)}><strong>{title}</strong><span>{note}</span></button>)}</section></>;
}
function AdminContent() {
  const view = new URLSearchParams(location.search).get("view") ?? "homepage"; const [saved, setSaved] = useState(false);
  return <><div className="admin-heading row"><div><h1>{view === "homepage" ? "Homepage Editor" : view === "products" ? "Product Display" : "Work Editor"}</h1><p>Edit structured content. Media remains in the merchant-owned asset store.</p></div><button className="primary" onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 1500); }}>{saved ? "Saved ✓" : "Save draft"}</button></div><section className="editor-layout"><div className="editor-preview"><img src={view === "works" ? "/assets/works/JINE_01.png" : "/assets/editorial/jine-hero.png"} alt="Content preview" /><div><p className="eyebrow">LIVE PREVIEW</p><h2>One Silhouette.<br />Endless Expressions.</h2></div></div><form className="editor-form"><label>Internal title<input defaultValue={view === "homepage" ? "Homepage · 2026 Runway" : "JINÉ · Moon White"} /></label><label>Eyebrow<input defaultValue="RUNWAY FILM · 01" /></label><label>Master copy · 简中<textarea rows={4} defaultValue="同一廓形，无尽表达。" /></label><label>Master copy · English<textarea rows={4} defaultValue="One Silhouette. Endless Expressions." /></label><label>Visibility<select><option>Published</option><option>Draft</option><option>Scheduled</option></select></label></form></section></>;
}
function AdminSku() {
  const [steps, setSteps] = useState(["Fabric", "Lining", "Trims", "Craft", "Review"]); const [selected, setSelected] = useState(1); const move = (direction: number) => setSteps((current) => { const next = [...current]; const target = selected + direction; if (target < 0 || target >= next.length) return current; [next[selected], next[target]] = [next[target], next[selected]]; setSelected(target); return next; });
  return <><div className="admin-heading row"><div><h1>SKU Step Builder</h1><p>JINÉ · JN-01-MW · {steps.length} steps</p></div><button className="primary">保存草稿</button></div><section className="sku-builder"><div className="step-list"><span>Steps · select to edit</span>{steps.map((item, index) => <button className={selected === index ? "active" : ""} key={item} onClick={() => setSelected(index)}><i>≡</i><b>{String(index + 1).padStart(2, "0")}</b>{item}<small>{index === steps.length - 1 ? "System" : index === 3 ? "Optional" : "Required"}</small></button>)}<div className="reorder"><button onClick={() => move(-1)}>Move up</button><button onClick={() => move(1)}>Move down</button></div></div><form className="step-editor"><h2>Step {String(selected + 1).padStart(2, "0")} · {steps[selected]}</h2><label>Internal key<input defaultValue={steps[selected].toLowerCase()} /></label><label>Labels<input defaultValue={`zh-CN 选择${steps[selected]} · en Select ${steps[selected].toLowerCase()} · ja 選択`} /></label><label>Selection type<select><option>Single select</option><option>Multiple select</option></select></label><label>Requirement<select><option>Required</option><option>Optional</option><option>System</option></select></label><label>Draft behaviour<select><option>Auto-save on valid selection</option></select></label><label>Invalidation<input defaultValue="Require reconfirmation if option is removed" /></label></form></section></>;
}
function AdminTranslations() {
  const [live, setLive] = useState(true); const rows = [["Title", "JINÉ 01", "JINÉ 01", "JINÉ 01", "JINÉ 01"], ["Subtitle", "月白真丝", "Moon White Silk", "月白真絲", "月白のシルク"], ["Positioning", "静奢经典系列", "Quiet luxury classic", "靜奢經典系列", "静かなラグジュアリー"], ["Order CTA", "开始订购", "Begin order", "開始訂購", "注文を開始"]];
  return <><div className="admin-heading row"><div><h1>Translations & Publishing</h1><p>Two master copies · instant derived locales · language-skill</p></div><span className="live-status">{live ? "100% live" : "Draft changes"}</span></div><div className="source-rule"><span>P0 · COPY SOURCE RULE</span><h2>简体中文 + English = 唯一主文案</h2><p>繁體中文 ← 简体中文机器翻译　日本語及其他非中文 ← English 机器翻译</p></div><div className="translation-table"><div className="translation-row head"><span>FIELD</span><span>简中 · MASTER</span><span>EN · MASTER</span><span>繁中 · FROM 简</span><span>日本語 · FROM EN</span></div>{rows.map((row) => <div className="translation-row" key={row[0]}>{row.map((cell, index) => <span key={`${index}-${cell}`}>{cell}</span>)}</div>)}</div><section className="locale-cards">{[["简中", "MASTER · editable"], ["English", "MASTER · editable"], ["繁中", "DERIVED FROM 简"], ["日本語", "DERIVED FROM EN"]].map(([name, status], index) => <article className={index < 2 ? "master" : ""} key={name}><h3>{name}</h3><p>{status}</p><span>{index < 2 ? "即时发布" : "自动重译 · 无需审核"}</span></article>)}</section><div className="admin-actions"><button className="primary" onClick={() => setLive(true)}>保存并即时发布</button><button className="secondary" onClick={() => setLive(false)}>重新生成派生语言</button></div></>;
}
function AdminOrders() {
  const [orders, setOrders] = useState<any[]>([]); const [connected, setConnected] = useState(false); useEffect(() => { apiFetch("/api/projects").then((projects) => { setConnected(true); setOrders(Array.isArray(projects) ? projects : []); }).catch(() => undefined); }, []); const fallback = [{ id: "JN-260726-018", title: "JINÉ · Moon White", status: "CONFIRMED", created_at: "2026-07-26" }, { id: "NS-260804-006", title: "NÉSHA · Living Art", status: "PRODUCTION", created_at: "2026-08-04" }, { id: "JN-260817-024", title: "JINÉ · Platinum Grey", status: "AWAITING", created_at: "2026-08-17" }]; const shown = orders.length ? orders : fallback;
  return <><div className="admin-heading"><h1>Orders</h1><p>{connected ? "Live Giraffe-JP project data" : "Preview data · connect VITE_API_URL for live projects"}</p></div><div className="orders-toolbar"><input placeholder="Search order or customer" /><select><option>All statuses</option><option>Awaiting</option><option>Confirmed</option><option>Production</option></select></div><div className="orders-table"><div className="orders-row head"><span>Order</span><span>Work</span><span>Status</span><span>Created</span><span /></div>{shown.map((order) => <div className="orders-row" key={order.id}><span>{order.id}</span><strong>{order.title}</strong><span><i className={`status ${String(order.status).toLowerCase()}`}>{order.status}</i></span><span>{new Date(order.created_at).toLocaleDateString()}</span><button>Open →</button></div>)}</div></>;
}
function AdminPage({ path, navigate }: { path: string; navigate: (to: string) => void }) {
  if (path === "/admin/login") return <AdminLogin navigate={navigate} />; let content: ReactNode = <AdminDashboard navigate={navigate} />; if (path === "/admin/content") content = <AdminContent />; if (path === "/admin/sku") content = <AdminSku />; if (path === "/admin/translations") content = <AdminTranslations />; if (path === "/admin/orders") content = <AdminOrders />; return <AdminShell navigate={navigate}>{content}<button className="admin-logout" onClick={() => { clearToken(); navigate("/admin/login"); }}>Sign out</button></AdminShell>;
}
function NotFound({ navigate }: { navigate: (to: string) => void }) { return <section className="not-found"><p>404</p><h1>This page is not part of the collection.</h1><button className="primary" onClick={() => navigate("/")}>Return home</button></section>; }

export default function App() {
  const { path, navigate } = usePath(); const [locale, setLocale] = useState<Locale>(() => (localStorage.getItem("jn-locale") as Locale) || "zh-CN"); useEffect(() => { localStorage.setItem("jn-locale", locale); document.documentElement.lang = locale; }, [locale]);
  return useMemo(() => { if (path.startsWith("/admin")) return <AdminPage path={path} navigate={navigate} />; let page: ReactNode; if (path === "/") page = <Home locale={locale} navigate={navigate} />; else if (path === "/works") page = <WorksPage locale={locale} navigate={navigate} />; else if (/^\/works\/[a-z]+-\d+$/.test(path)) page = <WorkDetail id={path.split("/").pop()!} locale={locale} navigate={navigate} />; else if (path === "/silhouette") page = <SilhouettePage />; else if (path === "/materials") page = <MaterialsPage />; else if (path === "/atelier") page = <AtelierPage />; else if (path === "/appointment") page = <AppointmentPage />; else if (path.startsWith("/configure/")) page = <Configurator workId={path.split("/").pop()!} locale={locale} navigate={navigate} />; else if (path === "/account") page = <CustomerCentre locale={locale} navigate={navigate} />; else if (path.startsWith("/orders/")) page = <OrderDetail />; else page = <NotFound navigate={navigate} />; return <SiteShell locale={locale} onLocale={setLocale} navigate={navigate}>{page}</SiteShell>; }, [path, locale]);
}
